/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.Produkcija;

import Connection.Session;
import controller.ClientController;
import domen.Glumac;
import domen.Izabrani;
import domen.Produkcija;
import domen.Projekat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import modeli.ModelFinal;
import modeli.ModelRezervacija;

/**
 *
 * @author Panda
 */
public class ProjekatForma extends javax.swing.JFrame {

    Produkcija ulogovan;
    ModelFinal modelF;
    GlavnaP gp;

    
    
    public ProjekatForma() {
        initComponents();
        ulogovan = (Produkcija) Session.getInstance().getTrenutnoUlogovan();
        setLocationRelativeTo(null);
        ModelRezervacija modelR = new ModelRezervacija();
        tabelaRezervacije.setModel(modelR);

        modelF = new ModelFinal();
        tabelaFinal.setModel(modelF);
    }
    
    public GlavnaP getGp() {
        return gp;
    }

    public void setGp(GlavnaP gp) {
        this.gp = gp;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtImeProjekta = new javax.swing.JTextField();
        cmbUloga = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRezervacije = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFinal = new javax.swing.JTable();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ime projekta:");

        txtImeProjekta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeProjektaActionPerformed(evt);
            }
        });

        cmbUloga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Glavni muska uloga", "Glavna zenska uloga", "Sporedna 1", "Sporedna 2", "Sporedna 3" }));

        tabelaRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaRezervacije);

        jButton1.setText("Rezervisi Glumca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Trenutna postava projekta");

        tabelaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaFinal);

        btnSacuvaj.setText("Sacuvaj Projekat");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(txtImeProjekta, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(296, 296, 296)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmbUloga, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImeProjekta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbUloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeProjektaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeProjektaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeProjektaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String uloga = (String) cmbUloga.getSelectedItem();
            
            int izabrani = tabelaRezervacije.getSelectedRow();
            Glumac glumac = ClientController.getInstance().getAllGlumci().get(izabrani);
            
            Izabrani i = new Izabrani(glumac,uloga);
            modelF.dodajIzabranog(i);
        } catch (Exception ex) {
            Logger.getLogger(ProjekatForma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String imeProjekta = txtImeProjekta.getText();
        ArrayList<Izabrani> izabrani = modelF.getIzabrani();
        int gm = 1;
        int gz = 1;
        int s1 = 1;
        int s2 = 1;
        int s3 = 1;
        for(Izabrani i : izabrani) {
            if(i.getUloga() == "Glavni muska uloga")
                gm = i.getG().getGlumacID();
            else if(i.getUloga() == "Glavna zenska uloga")
                gz = i.getG().getGlumacID();
            else if(i.getUloga() == "Sporedna 1")
                s1 = i.getG().getGlumacID();
            else if(i.getUloga() == "Sporedna 2")
                s2 = i.getG().getGlumacID();
            else if(i.getUloga() == "Sporedna 3")
                s3 = i.getG().getGlumacID();
        }
        Projekat p = new Projekat(imeProjekta, gm, gz, s1, s2, s3, ulogovan.getProdukcijaID());
        try {
            ClientController.getInstance().createProjekat(p);
        } catch (Exception ex) {
            Logger.getLogger(ProjekatForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            gp.okinava();
        } catch (Exception ex) {
            Logger.getLogger(ProjekatForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        
//Glavni muska uloga
//Glavna zenska uloga
//Sporedna 1
//Sporedna 2
//Sporedna 3
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> cmbUloga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaFinal;
    private javax.swing.JTable tabelaRezervacije;
    private javax.swing.JTextField txtImeProjekta;
    // End of variables declaration//GEN-END:variables
}
